dofile("libs/chud.lua")
dofile("libs/glchud.lua")
dofile("libs/wad.lua")
dofile("libs/doomgfx.lua")
dofile("libs/doomflat.lua")

dofile("doom.lua")
dofile("maplumps.lua")
dofile("map.lua")
dofile("bsp.lua")
dofile("mobj.lua")
dofile("camera.lua")
dofile("texture.lua")
dofile("renderer.lua")
dofile("patches.lua")
dofile("menu.lua")
dofile("wipe.lua")
dofile("status.lua")

dofile("main.lua")